# Set master image
FROM php:7.3-fpm

# Set working directory
WORKDIR /var/www

# Install Additional dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    procps \
    nano \
    unzip \
    libjpeg-dev \
    libpng-dev \
    libxpm-dev \
    libfreetype6-dev \
    libicu-dev \
    zlib1g-dev \
    libxml2 \
    libxml2-dev \
    libreadline-dev \
    supervisor \
    cron \
    libzip-dev \
    && pecl install redis \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ \
    --with-xpm-dir=/usr/include/ \
    && docker-php-ext-install \
    bcmath \
    gettext \
    pdo \
    pdo_mysql \
    intl \
    opcache \
    soap \
    gd \
    zip && \
    rm -fr /tmp/* && \
    rm -rf /var/list/apt/* && \
    rm -r /var/lib/apt/lists/* && \
    apt-get clean \
    && rm -r /var/www \
    && mkdir -p /var/www/public \
    && usermod -u 1000 www-data && groupmod -g 1000 www-data \
    && chown -R www-data:www-data /var/www \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# Enable Extenstions
RUN docker-php-ext-enable redis

# Install xdebug
RUN pecl install xdebug-2.9.8 && docker-php-ext-enable xdebug

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt install nodejs

RUN npm install --global gulp-cli

# Remove Cache
RUN rm -rf /var/cache/apk/*

# Change current user to www-data
USER www-data

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]